[title]
en = "Education"
fr = "Éducation"

[body]
en = """
Learning through projects is arguably the best way to learn programming; however, solely learning through projects will leave you without the theoretical basis on which programming knowledge thrives. Indeed, I believe that learning about core topics in mathematics, engineering, and computer science will allow a software engineer to understand *why* something works or *how* to make it work, faster, making them better at what they do.

You will find information about my educational curriculum below.
"""
fr = """
Apprendre à travers des projets est possiblement une des meilleurs façons d'apprendre la programmation. Par contre, quelqu'un qui apprend seulement avec des projets va manquer la base théorique nécéssaire pour profiter du plein potentiel des connaissances en programmation. En effet, je pense qu'apprendre les concepts majeurs en mathématiques, ingéniérie et en science informatique va permettre à un.e ingénieur.e logiciel de comprendre *pourquoi* quelque chose fonctionne ou *comment* le faire fonctionner et cela plus vite, le.a rendant meilleur.e à son métier.

Vous en apprendrez plus sur mon curriculum éducationnel ci-dessous.
"""
